### ISSUE TITLE
`opam install ogen` fails (issue with ogen 0.1.2, ppx_deriving 4.0, ppx_deriving_yojson 3.0)

### ISSUE THREAD

**Issue by erikmd** [nv-vn/opam-create#2] opened 2016-07-29 12:11 UTC
Hello,
Currently `ogen` does not install out-of-the-box with OPAM. Actually ogen 0.1.2 does not compile with ppx_deriving 4.0 and ppx_deriving_yojson 3.0 that were released on last month. However, ogen 0.1.2 is fine with ppx_deriving 3.3 and ppx_deriving_yojson 2.4. I solved the issue locally by using `opam pin add` but I guess that https://github.com/ocaml/opam-repository/blob/master/packages/ogen/ogen.0.1.2/opam would need some update.
Best regards

P.S. For the record, here is the error that pops up:

``` bash
# File "src/main.ml", line 29, characters 8-16:
# Error: This pattern matches values of type [? `Ok of 'a ]
#        but a pattern was expected which matches values of type
#          Metafile.meta Ppx_deriving_yojson_runtime.error_or =
#            (Metafile.meta, string) Result.result
# Command exited with code 2.
```

**Comment by nv-vn** [comment] 2016-07-30 04:20
Ah right, thanks for pointing this out. I know what the problem is, but I forgot to make the preemptive move to fix this. I'm not really somewhere that I'm able to work on this at the moment, so the earliest I can work on this is probably Sunday. Anyways, I'll go ahead and assign it to myself for now and hopefully I'll remember to fix it this weekend.

**Comment by erikmd** [comment] 2016-07-30 22:12
OK thanks for your quick reply!

**Comment by nv-vn** [comment] 2016-07-31 06:02
Just submitted [a PR](https://github.com/ocaml/opam-repository/pull/7091) for opam-repository with this fix. I'll closed this issue once it gets merged and I confirm the fix worked.

**Comment by erikmd** [comment] 2016-07-31 17:50
Hi @nv-vn,
Thanks for your bugfix and for the new release! According to Travis it compiles smoothly with OCaml 4.03.
However part of the issue remains for OCaml 4.02 (sorry I forgot to mention I'm using OCaml 4.02.3):
`opam install ogen` stills fails trying to install ogen 0.1.2.
I believe that it would suffice to replace

```
  "ppx_deriving" {>= "3.0"}
  "ppx_deriving_yojson" {>= "2.4"}
```

with

```
  "ppx_deriving" {>= "3.0" & < "4.0"}
  "ppx_deriving_yojson" {>= "2.4" & < "3.0"}
```

in https://github.com/ocaml/opam-repository/blob/master/packages/ogen/ogen.0.1.2/opam
Tell me if you want that I submit another PR for that.
Cheers

**Comment by nv-vn** [comment] 2016-07-31 18:17
Oh, I didn't realize that. I thought the changes to ppx_deriving_yojson were only for 4.03.0+. I can't submit a PR at the moment (as I'm on my phone), so if you want to do it that would be incredibly helpful. If not, I can probably get it done in 2-3 hours. Either way, thanks for helping me work this out :)

**Comment by erikmd** [comment] 2016-07-31 19:26
Hi @nv-vn, indeed it appears that ppx_deriving_yojson 3.0 works will OCaml 4.02 as well.
So I've submitted a [new PR](https://github.com/ocaml/opam-repository/pull/7093) and you'll be able to close this issue after it is merged.
Best regards

**Comment by erikmd** [comment] 2016-07-31 22:09
All Travis builds passed with both OCaml 4.02 and 4.03, so IINM the last thing left to do will be to update the opam file in the master of your repo https://github.com/nv-vn/ogen/blob/master/opam#L15
Best regards

**Comment by nv-vn** [comment] 2016-08-01 03:01
Just changed it. Closing the issue now -- thanks for all the help :)

**Closed as completed by nv-vn** 2016-08-01 03:01 UTC
Labels: bug

**Comment by erikmd** [comment] 2016-08-01 21:03
Hi @nv-vn, you're welcome, thanks for contributing this nice package.
A very last suggestion regarding https://github.com/nv-vn/ogen/blob/master/opam#L15: maybe you could just put `ocaml-version >= "4.02"`?
so upcoming releases of `ogen` will benefit to users of OCaml 4.02.x too.
(BTW I've just re-tested `opam install ogen` and it is OK with OCaml 4.02.3)
Best regards

**Comment by nv-vn** [comment] 2016-08-01 23:15
Done :)
